### ISSUE TITLE
Can't get data usage from HH5

### ISSUE THREAD

**Issue by StormTrooper** [SorX14/Projects#1]
I've started using your script on my BT HH5A and its returning the version info correctly, but the uptime and  datausge is blank? Also the last update time doesn't seem to be correct?

Home Hub 5A statistics

Uptime (s):

Data usage (sent/received MB):

Version: 4.7.5.1.83.8.204.1.11 |

Last update: 02/07/15

**Comment by SorX14** [comment]
These figures are extracted with regex, so perhaps BT have changed the layout of the page. I should be able to take a look at this later.

**Comment by StormTrooper** [comment]
Thanks - that's quite possible. Also busy trying to hack my way around. 
I have seen the page number ID's have changed.

I've updated them but didn't help. Will keep poking around in the mean  
time.

```
     const SETTINGS_WIRELESS = 9101;
     const SETTINGS_ACCESS_CONTROL = 9115;
     const SETTINGS_PORT_FORWARDING = 9105;
     const SETTINGS_HUB_LIGHTS = 9130;
     const SETTINGS_BROADBAND = 9116;
     const SETTINGS_ADMIN_PASSWORD = 9125;

     const ADVANCED_SETTINGS_CONTINUE = 9099;
     const ADVANCED_WIRELESS_PAGE_24G = 9102;
     const ADVANCED_WIRELESS_PAGE_5G = 9103;
     const ADVANCED_WIRELESS_PAGE_WPS = 9104;
     const ADVANCED_BROADBAND_INTERNET = 9119;
     const ADVANCED_BROADBAND_CONNECTION = 9120;
     const ADVANCED_BROADBAND_VPN = 9121;
     const ADVANCED_BROADBAND_DYNAMIC_DNS = 9123;
     const ADVANCED_BROADBAND_IPV6_STATUS = 9124;

     const HOMENETWORK_DEVICES = 9131;
     const HOMENETWORK_SMART_SETUP = 9136;
     const HOMENETWORK_IP_ADDRESS = 9137;
     const HOMENETWORK_IPV6_CONFIGURATION = 9139;
     const HOMENETWORK_DHCP_TABLE = 9138;

     const FIREWALL_PORT_FORWARDING = 9106;
     const FIREWALL_UPNP = 9111;
     const FIREWALL_DMZ = 9112;
     const FIREWALL_IPV6_PINHOLES = 9113;
     const FIREWALL_CONFIGURATION = 9114;

     const SYSTEM_RESTART = 9126;
     const SYSTEM_BACKUP_RESTORE = 9127;
     const SYSTEM_RESET = 9128;

     const TROUBLESHOOTING_HELP_AND_ADVICE = 9140;
     const TROUBLESHOOTING_HELPDESK = 9141;
     const TROUBLESHOOTING_EVENT_LOG = 9142;
```

**Comment by SorX14** [comment]
I can't update the repo from here, but, the one to change is:

`const LOGIN = 9146;`

And then your change to `TROUBLESHOOTING_HELPDESK` will work.

**Comment by StormTrooper** [comment]
Awesome! Thanks - that did the trick. All working now.

**Comment by SorX14** [comment]
Updated the repo, I'll mark this as closed
